CREATE DATABASE IF NOT EXISTS TEMP; 
USE TEMP ;
CREATE TABLE IF NOT EXISTS account (
 AC_NO INT PRIMARY KEY UNIQUE,
 NAME VARCHAR(255),
 BALANCE INT(255) NOT NULL DEFAULT 0
-- CONSTRAINT acc_balance CHECK (balance > 1000)
);
-- ADD NEW COLUMN IN TABLE ----------
-- ALTER TABLE account ADD interest FLOAT NOT NULL DEFAULT 0;
-- MODIFY DATA TYPE ------
ALTER TABLE account MODIFY interest DOUBLE NOT NULL DEFAULT 0;
-- RENAME THE COLUMNS ----------
ALTER TABLE account CHANGE COLUMN interest saving_interest FLOAT NOT NULL DEFAULT 0;
DESC ACCOUNT;
   SELECT * FROM account;                 