
USE comapny;
-- SELECT * FROM worker WHERE DEPARTMENT = "hr";
-- WHERE AND BETWEEN EXAMPLE
-- SELECT * FROM worker WHERE SALARY BETWEEN 25000 AND 30000;
-- OR STATEMENT REDUCING
-- HR AND ADMIN TUPLE PRINT
-- SELECT * FROM worker WHERE DEPARTMENT = "HR" OR DEPARTMENT = "ADMIN"; 
-- SELECT * FROM 	worker WHERE DEPARTMENT IN ("HR","ADMIN","ACCOUNT");
-- SELECT * FROM 	worker WHERE DEPARTMENT NOT IN ("HR");


