CREATE DATABASE IF NOT EXISTS TEMP; 
USE TEMP ;
CREATE TABLE IF NOT EXISTS account (
 AC_NO INT PRIMARY KEY UNIQUE,
 NAME VARCHAR(255),
 BALANCE INT(255) NOT NULL DEFAULT 0
-- CONSTRAINT acc_balance CHECK (balance > 1000)
);
-- ADD NEW COLUMN IN TABLE ----------
-- ALTER TABLE account ADD interest FLOAT NOT NULL DEFAULT 0;
-- MODIFY DATA TYPE ------
ALTER TABLE account MODIFY interest DOUBLE NOT NULL DEFAULT 0;
-- RENAME THE COLUMNS ----------
ALTER TABLE account CHANGE COLUMN interest saving_interest FLOAT NOT NULL DEFAULT 0;
DESC ACCOUNT;
ALTER TABLE account RENAME TO account_details;
   SELECT * FROM account;                 
   SELECT DISTINCT Department FROM worker;
-- GROUP BY
-- SELECT DEPARTMENT, COUNT(*) FROM worker GROUP BY DEPARTMENT;
-- SELECT department, COUNT(department) FROM worker GROUP BY department;
-- AVG SALARY OR ALL EMPLOYEE BY EVERY DEPARTMENT
SELECT department, AVG(salary) FROM worker GROUP BY department;
-- MINIMUM SALARY 
SELECT department, MIN(salary) FROM worker GROUP BY department HAVING Count(Department)>2;
